### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by kenshinhm** [SHI-Labs/Pyramid-Attention-Networks#10]
Hello, Thank you for publicizing code for great work.
I was wondering, how can we prepare demosaic dataset from div2k training set?
or denoise dataset with different noise variation ?
where can we find such script for it??

**Comment by HarukiYqM** [comment]
> Hello, Thank you for publicizing code for great work.
> I was wondering, how can we prepare demosaic dataset from div2k training set?
> or denoise dataset with different noise variation ?
> where can we find such script for it??

Hi, we use the matlab scripts from https://github.com/cszn/IRCNN

**Comment by kenshinhm** [comment]
Thanks !!
