### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by tao-qingyang** [SHI-Labs/Pyramid-Attention-Networks#11]
作者您好，请问数据集文件夹中的x10x30x50x70是如何整理的啊，我下载下来的数据集里是x2x3x4

**Comment by HarukiYqM** [comment]
您好， x2/x3/x4 是针对sr的。 x10/x30/x50/x70 是针对denoise的。可以使用ircnn中的script https://github.com/cszn/IRCNN 处理div2k HR 生成相关的训练图片。
