### ISSUE TITLE
有关论文中图8的绘制问题

### ISSUE THREAD

**Issue by AlexZou14** [SHI-Labs/Pyramid-Attention-Networks#13]
请问一下论文中图8 Visualization of correlation maps of pyramid attention是怎么画的，希望作者您能将代码开源到这个项目中。

**Comment by AlexZou14** [comment]
希望作者大佬尽快恢复，非常感谢

**Comment by HarukiYqM** [comment]
> 请问一下论文中图8 Visualization of correlation maps of pyramid attention是怎么画的，希望作者您能将代码开源到这个项目中。

您好，这个很简单，拿到attention score的数组以后直接用matplotlib.pyplot show image 就可以。
