### ISSUE TITLE
RGB图像的SSIM和PSNR的求得

### ISSUE THREAD

**Issue by MC-E** [SHI-Labs/Pyramid-Attention-Networks#15]
您好，我想知道论文中去马赛克任务的PSNR和SSIM是如何求出的，python和matlab的结果有较大的差别。谢谢，期待您的回复。

**Comment by HarukiYqM** [comment]
> 您好，我想知道论文中去马赛克任务的PSNR和SSIM是如何求出的，python和matlab的结果有较大的差别。谢谢，期待您的回复。

不好意思，回复较晚。我们使用的RNAN(https://github.com/yulunzhang/RNAN/) 的matlab script进行的测试。
