### ISSUE TITLE
test on arbitraty images?

### ISSUE THREAD

**Issue by eps696** [SHI-Labs/Pyramid-Attention-Networks#2]
is there dataloader for just a folder of images?

**Comment by HarukiYqM** [comment]
You can test on arbitrary images by taking following steps:
1. Put your images in a folder (e.g. test)
2. Set “—dir_demo path_to_your_folder” and “—data_test Demo” 
For example, for SR x2 your can run following command:
python main.py --model PAEDSR --dir_demo path_to_your_folder --data_test   Demo --save_results --rgb_range 1 --scale 2 --n_feats 256 --n_resblocks 32 --res_scale 0.1 --pre_train ../model_x2.pt --test_only --chop

**Comment by eps696** [comment]
thank you
