### ISSUE TITLE
SR pretrained models

### ISSUE THREAD

**Issue by alvin-p** [SHI-Labs/Pyramid-Attention-Networks#22]
I have downloaded the pretrained models for SR (x4) from google drive and tested them on Set5, Set14 and Urban100, however I do not achieve the PSNR/SSIM results from the paper. Are the model weights on google drive the correct ones?

**Comment by HarukiYqM** [comment]
Hi, if you correctly follow the instructions, it should exactly reproduce the results in paper. Please use this codebase to avoid any version problems when load pretrained models.
Here is my results:
![Screenshot from 2021-04-24 16-44-23](https://user-images.githubusercontent.com/30628038/115953168-63fb1a00-a51c-11eb-98c9-b22b01786eb8.png)


You can also double check the results by first inference the outputs and evaluate the results using third party code like (https://github.com/yulunzhang/RNAN/blob/master/SR/experiment/PP_Evaluate_SR.m).

**Comment by HarukiYqM** [comment]
> Hi, if you follow the instructions, it should reproduce the results in paper. It may be possible to have a very slight differences which is up to (+-0.01), since we often re-train the model with the final released version of the code, where the differences is due to the stochastic property of the optimization algorithm.

**Comment by alvin-p** [comment]
Thanks!
