### ISSUE TITLE
weird results

### ISSUE THREAD

**Issue by aligoglos** [SHI-Labs/Pyramid-Attention-Networks#3]
I tried to run SP code with some test images but results are like these :
![1_x4_SR](https://user-images.githubusercontent.com/3922472/80908808-34b23280-8d38-11ea-91f2-86234c486bf7.png)
input image :
![1](https://user-images.githubusercontent.com/3922472/80908813-3da30400-8d38-11ea-9a02-675b7b4c9a75.jpg)
I tried this script :
`python main.py --model PAEDSR --dir_demo ./inputs/ --data_test Demo --save_results --rgb_range 1 --scale 4 --n_feats 256 --n_resblocks 32 --res_scale 0.1 --pre_train model_x4.pt --test_only --chop`

**Comment by HarukiYqM** [comment]
Hi, i not sure why this happen. It seems that model weight is not load correctly. Could your try to download the weight again?
Here is my result in experiment/test/results-Demo/
![temp_x4_SR](https://user-images.githubusercontent.com/30628038/80910930-889d2700-8cf8-11ea-96c5-30b9b2364c5d.png)

**Comment by aligoglos** [comment]
Yes it solved.

**Comment by Yuineko1998** [comment]
I have the same problems，how did u solve it?
