### ISSUE TITLE
在SR中自己训练网络，验证过程缓慢？

### ISSUE THREAD

**Issue by LY54** [SHI-Labs/Pyramid-Attention-Networks#4]
您好，请问我用自己的数据集仿照DIV2K的格式，在单个GPU上运行您的SR模型中paedsr代码，验证过程运行了5个小时，一直没出结果？请问这正常吗？我是错过了什么吗？我是个新手，看您项目是在EDSR项目上的，我想问下训练语句中data_range设置为255和1的区别是什么？
#Train x2
python main.py --n_GPUs 1 --rgb_range 1 --reset --save_models --lr 1e-4 --decay 200-400-600-800 --chop --save_results --n_resblocks 32 --n_feats 256 --res_scale 0.1 --batch_size 16 --model PAEDSR --scale 2 --patch_size 96 --save EDSR_PA_x2 --data_train DIV2K

**Comment by HarukiYqM** [comment]
您好，
1.Validation应该很快。可能是您路径配置不正确，您可以将validation的图片也包含在hr/lr的文件夹件内，通过设置data_range 区分训练集和验证集。例如在DIV2K上，1-800为训练集，801-810为测试集 那么将data_range 设置为1-800/801-810。
parser.add_argument('--data_test', type=str, default='DIV2K',
                    help='test dataset name')
parser.add_argument('--data_range', type=str, default='1-800/801-810',
                    help='train/test data range')
2. rgb_range 1或者255 在效果上没有明显区别。
设为1会将0-255的RGB数值rescale到0-1的区间内。

**Comment by LY54** [comment]
好的，感谢您百忙中的解答，我近期会在尝试一下。

**Comment by scutlrr** [comment]
> 您好，请问我用自己的数据集仿照DIV2K的格式，在单个GPU上运行您的SR模型中paedsr代码，验证过程运行了5个小时，一直没出结果？请问这正常吗？我是错过了什么吗？我是个新手，看您项目是在EDSR项目上的，我想问下训练语句中data_range设置为255和1的区别是什么？
> #Train x2
> python main.py --n_GPUs 1 --rgb_range 1 --reset --save_models --lr 1e-4 --decay 200-400-600-800 --chop --save_results --n_resblocks 32 --n_feats 256 --res_scale 0.1 --batch_size 16 --model PAEDSR --scale 2 --patch_size 96 --save EDSR_PA_x2 --data_train DIV2K

您好，请问您的单GPU配置是多少的？训练了多久时间？

**Comment by House-Leo** [comment]
一样遇到这种问题，感觉是不是输入测试的图片分辨率太大了（2K）
