### ISSUE TITLE
关于训练CAR的问题

### ISSUE THREAD

**Issue by jeejeeli** [SHI-Labs/Pyramid-Attention-Networks#5]
您好：
        CAR小白~，我在看CAR的训练代码时，发现是把图像转成YUV，然后在Y通道上训练，我想问下是不是对于CAR任务，都是RGB转YUV，然后在Y通道上训练呢？，我能不能直接在RGB三通道上训练呢？或者说在Y通道上训练有什么好处呢，非常感谢您的回答，谢谢~~~

**Comment by RyanXingQL** [comment]
补充一个问题：如果将YUV concat输入，和Y U V分别增强，效果能否有所提升？感谢！类似地，RGB同时输入和R G B分别输入相比如何？

**Comment by HarukiYqM** [comment]
> 您好：
> CAR小白~，我在看CAR的训练代码时，发现是把图像转成YUV，然后在Y通道上训练，我想问下是不是对于CAR任务，都是RGB转YUV，然后在Y通道上训练呢？，我能不能直接在RGB三通道上训练呢？或者说在Y通道上训练有什么好处呢，非常感谢您的回答，谢谢~~~
您好，在Y通道训练的主要原因是为了和之前文章的实验设置保持一致，控制变量。您也可以尝试在RGB上直接训练

**Comment by HarukiYqM** [comment]
> 补充一个问题：如果将YUV concat输入，和Y U V分别增强，效果能否有所提升？感谢！类似地，RGB同时输入和R G B分别输入相比如何？

在YUV三通道中，Y对结果影响最为显著，所以有些方法只选择Y channel，例如VDSR。CAR实验为了和之前的方法进行公平比较所以使用了相同的实验设置。对于RGB，一般采取直接三通道RGB输入，或者转为YUV后对Y进行处理。对三通道分别处理我认为作用可能很微小。

**Comment by RyanXingQL** [comment]
感谢您的回复！还想请问您：CAR的demo中，scale设为40。对于一般的增强任务（无SR），是否将scale设为1就可以了呢？还有其他需要改动的吗？谢谢

**Comment by HarukiYqM** [comment]
> 感谢您的回复！还想请问您：CAR的demo中，scale设为40。对于一般的增强任务（无SR），是否将scale设为1就可以了呢？还有其他需要改动的吗？谢谢

您好，scale 这个参数主要是为了读取数据使用的，40 代表Q=40，对网络结果本身没有影响。

**Comment by RyanXingQL** [comment]
谢谢！还有一个问题：demo中的n_resblocks=80参数，test时可以随意更改吗？还是说，pretrained model就是在80个rb下训练的，不能更改？

**Comment by jeejeeli** [comment]
@HarukiYqM  谢谢您的回答

**Comment by HarukiYqM** [comment]
> 谢谢！
> 1、我在panet.py里看到，对于CAR任务，tail的upsample被注释掉了，所以scale对网络没有影响，对吗?
> 2、pannet.py会报错，可能存在问题：n_resblocks 应该改为：n_resblock？
> 3、关于速度问题。我正在处理1080p的图像，2080ti上一帧要40s。这个速度正常吗？而且大部分时间都在处理nonlocal。我正在考虑简化模型的问题。
> 谢谢！

**Comment by HarukiYqM** [comment]
> 谢谢！
> 1、我在panet.py里看到，对于CAR任务，tail的upsample被注释掉了，所以scale对网络没有影响，对吗?
> 2、pannet.py会报错，可能存在问题：n_resblocks 应该改为：n_resblock？
> 3、关于速度问题。我正在处理1080p的图像，2080ti上一帧要40s。这个速度正常吗？而且大部分时间都在处理nonlocal。我正在考虑简化模型的问题。
> 谢谢！
您好，
1. 是的
2. 您方便log贴上来吗？n_resblocks是正确的
3. 1080p 图片很大，单卡inference慢

**Comment by RyanXingQL** [comment]
> > 谢谢！
> > 1、我在panet.py里看到，对于CAR任务，tail的upsample被注释掉了，所以scale对网络没有影响，对吗?
> > 2、pannet.py会报错，可能存在问题：n_resblocks 应该改为：n_resblock？
> > 3、关于速度问题。我正在处理1080p的图像，2080ti上一帧要40s。这个速度正常吗？而且大部分时间都在处理nonlocal。我正在考虑简化模型的问题。
> > 谢谢！
> > 您好，
> 
> 1. 是的
> 2. 您方便把log贴上来吗？n_resblocks是正确的
> 3. 1080p 图片很大，基于attention的模型单卡inference可能会比较慢。如果显存足够，您可以通过增大在model/_init_.py 中chop_forward 的max_size 来加速或者多卡inference。简化模型提速可以考虑缩小resblock数量。

您看https://github.com/SHI-Labs/Pyramid-Attention-Networks/blob/master/CAR/code/model/panet.py的line 28 、line 31，n_resblocks貌似赋值~应该是n_resblock？

**Comment by HarukiYqM** [comment]
> > > 谢谢！
> > > 1、我在panet.py里看到，对于CAR任务，tail的upsample被注释掉了，所以scale对网络没有影响，对吗?
> > > 2、pannet.py会报错，可能存在问题：n_resblocks 应该改为：n_resblock？
> > > 3、关于速度问题。我正在处理1080p的图像，2080ti上一帧要40s。这个速度正常吗？而且大部分时间都在处理nonlocal。我正在考虑简化模型的问题。
> > > 谢谢！
> > > 您好，
> > 
> > 
> > 
> > 1. 是的
> > 2. 您方便把log贴上来吗？n_resblocks是正确的
> > 3. 1080p 图片很大，基于attention的模型单卡inference可能会比较慢。如果显存足够，您可以通过增大在model/_init_.py 中chop_forward 的max_size 来加速或者多卡inference。简化模型提速可以考虑缩小resblock数量。
> 
> 谢谢您的回复！
> 1、您看https://github.com/SHI-Labs/Pyramid-Attention-Networks/blob/master/CAR/code/model/panet.py 的line 28 、line 31，n_resblocks没有赋值，报错了。应该是n_resblock？
> 2、 您说的是init.py -> forward_chop里的min_size吗？我看了看，好像是将图像切块，然后min_size就是一个patch的最大尺寸？除此之外min_size设置有什么要求吗，可以随意设置吗？^ ^麻烦您了

您好，
1. 不好意思，确实是整理代码时出现的typo。感谢指出bug。现在已经更新。
2.是的，min_size是切块的最大尺寸。您可以修改/增加这个参数来充分利用您的显存。

**Comment by RyanXingQL** [comment]
> > > > 谢谢！
> > > > 1、我在panet.py里看到，对于CAR任务，tail的upsample被注释掉了，所以scale对网络没有影响，对吗?
> > > > 2、pannet.py会报错，可能存在问题：n_resblocks 应该改为：n_resblock？
> > > > 3、关于速度问题。我正在处理1080p的图像，2080ti上一帧要40s。这个速度正常吗？而且大部分时间都在处理nonlocal。我正在考虑简化模型的问题。
> > > > 谢谢！
> > > > 您好，
> > > 
> > > 
> > > 
> > > 1. 是的
> > > 2. 您方便把log贴上来吗？n_resblocks是正确的
> > > 3. 1080p 图片很大，基于attention的模型单卡inference可能会比较慢。如果显存足够，您可以通过增大在model/_init_.py 中chop_forward 的max_size 来加速或者多卡inference。简化模型提速可以考虑缩小resblock数量。
> > 
> > 
> > 谢谢您的回复！
> > 1、您看https://github.com/SHI-Labs/Pyramid-Attention-Networks/blob/master/CAR/code/model/panet.py 的line 28 、line 31，n_resblocks没有赋值，报错了。应该是n_resblock？
> > 2、 您说的是init.py -> forward_chop里的min_size吗？我看了看，好像是将图像切块，然后min_size就是一个patch的最大尺寸？除此之外min_size设置有什么要求吗，可以随意设置吗？^ ^麻烦您了
> 
> 您好，
> 
> 1. 不好意思，确实是整理代码时出现的typo。感谢指出bug。现在已经更新。
>    2.是的，min_size是切块的最大尺寸。您可以修改/增加这个参数来充分利用您的显存。

非常非常感谢！

**Comment by RyanXingQL** [comment]
作者您好，CAR demo train命令中，`---save_models`应改为`--save_models`~
