### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by RyanXingQL** [SHI-Labs/Pyramid-Attention-Networks#6]
作者您好：
1、CAR demo train命令中，`---save_models`应改为`--save_models`~

2、此外还想问您一个问题：您是如何训练y通道的呢（数据如何输入）？是直接将Y通道保存为png存储吗？
我自己准备了数据库，HQ（high-quality）和LQ图像都是Y通道存为png格式。此处（https://github.com/SHI-Labs/Pyramid-Attention-Networks/blob/113b6ac44b1198c56f7dedb6efab6aa449b47ef3/CAR/code/data/srdata.py#L78） 是否应该改为self.ext[0]（1对应jpg，0对应png）？

不胜感激！

**Comment by HarukiYqM** [comment]
> 作者您好：
> 1、CAR demo train命令中，`---save_models`应改为`--save_models`~
> 
> 2、此外还想问您一个问题：您是如何训练y通道的呢（数据如何输入）？是直接将Y通道保存为png存储吗？
> 我自己准备了数据库，HQ（high-quality）和LQ图像都是Y通道存为png格式。此处（[https://github.com/SHI-Labs/Pyramid-Attention-Networks/blob/113b6ac44b1198c56f7dedb6efab6aa449b47ef3/CAR/code/data/srdata.py#L78）](https://github.com/SHI-Labs/Pyramid-Attention-Networks/blob/113b6ac44b1198c56f7dedb6efab6aa449b47ef3/CAR/code/data/srdata.py#L78%EF%BC%89) 是否应该改为self.ext[0]（1对应jpg，0对应png）？
> 
> 不胜感激！

您好，感谢您指出问题。如果您按照Doc里面说的组织数据的话，应该可以直接读取，不需要改ext。或者您也可以写一个自己的Dataset Class
