### ISSUE TITLE
testing issues for demosaicking

### ISSUE THREAD

**Issue by amnesiack** [SHI-Labs/Pyramid-Attention-Networks#7]
Hello,

thank you for making the code public available.
I test demosaicking with the kodak dataset and the results look like somehow over-exposed. Do you have any idea what happened or something I did wrong?

![kodim01_x1_DM](https://user-images.githubusercontent.com/25249388/83037265-e0028e80-a03b-11ea-8c6b-4c1973507147.png)

I follow the instructions, download the pretrained models and run testing with the following line.
python main.py --model PANET --save_results --n_GPUs 1 --chop --n_resblocks 80 --n_feats 64 --data_test Kodak24 --scale 1 --pre_train ../model_best.pt --test_only --save_gt

And the visual results of kodak dataset provided in google drive is also 500*500. The original resolution of them is 512*768, is there any downsampling performed or just cropping and is the testing results shown in the paper also based on the 500*500 version?

Sorry for so many questions and thanks in advance,
Kai

**Comment by HarukiYqM** [comment]
> Hello,
> 
> thank you for making the code public available.
> I test demosaicking with the kodak dataset and the results look like somehow over-exposed. Do you have any idea what happened or something I did wrong?
> 
> ![kodim01_x1_DM](https://user-images.githubusercontent.com/25249388/83037265-e0028e80-a03b-11ea-8c6b-4c1973507147.png)
> 
> I follow the instructions, download the pretrained models and run testing with the following line.
> python main.py --model PANET --save_results --n_GPUs 1 --chop --n_resblocks 80 --n_feats 64 --data_test Kodak24 --scale 1 --pre_train ../model_best.pt --test_only --save_gt
> 
> And the visual results of kodak dataset provided in google drive is also 500_500. The original resolution of them is 512_768, is there any downsampling performed or just cropping and is the testing results shown in the paper also based on the 500*500 version?
> 
> Sorry for so many questions and thanks in advance,
> Kai

Hi, Kodak24 datasets in this work are taken from https://github.com/cszn/FFDNet/tree/master/testsets/Kodak24. For overexposure problem, how did you create mosaic images?

**Comment by amnesiack** [comment]
> 
> Hi, Kodak24 datasets in this work are taken from https://github.com/cszn/FFDNet/tree/master/testsets/Kodak24. For overexposure problem, how did you create mosaic images?

Thanks for your reply. I create a RGGB pattern mosaicked image and then interpolate it with the bicubic kernel. Do you also use RGGB and interpolation or just leave missing pixels blank?

**Comment by HarukiYqM** [comment]
> > Hi, Kodak24 datasets in this work are taken from https://github.com/cszn/FFDNet/tree/master/testsets/Kodak24. For overexposure problem, how did you create mosaic images?
> 
> Thanks for your reply. I create a RGGB pattern mosaicked image and then interpolate it with the bicubic kernel. Do you also use RGGB and interpolation or just leave missing pixels blank?

Hi, to create mosaic images, we use the code from IRCNN: https://github.com/cszn/IRCNN/blob/master/utilities/mosaic_bayer.m

**Comment by amnesiack** [comment]
> > > Hi, Kodak24 datasets in this work are taken from https://github.com/cszn/FFDNet/tree/master/testsets/Kodak24. For overexposure problem, how did you create mosaic images?
> > 
> > 
> > Thanks for your reply. I create a RGGB pattern mosaicked image and then interpolate it with the bicubic kernel. Do you also use RGGB and interpolation or just leave missing pixels blank?
> 
> Hi, to create mosaic images, we use the code from IRCNN: https://github.com/cszn/IRCNN/blob/master/utilities/mosaic_bayer.m with pattern 'grbg'

I see, the missing pixels are set to zeros and grbg pattern is generated. Now it works like a charm. Thanks a lot!

**Comment by HarukiYqM** [comment]
> > > > Hi, Kodak24 datasets in this work are taken from https://github.com/cszn/FFDNet/tree/master/testsets/Kodak24. For overexposure problem, how did you create mosaic images?
> > > 
> > > 
> > > Thanks for your reply. I create a RGGB pattern mosaicked image and then interpolate it with the bicubic kernel. Do you also use RGGB and interpolation or just leave missing pixels blank?
> > 
> > 
> > Hi, to create mosaic images, we use the code from IRCNN: https://github.com/cszn/IRCNN/blob/master/utilities/mosaic_bayer.m with pattern 'grbg'
> 
> I see, the missing pixels are set to zeros and grbg pattern is generated. Now it works like a charm. Thanks a lot!

Hi, we have updated our results  on original Kodak24.
