### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by jiandandan001** [SHI-Labs/Pyramid-Attention-Networks#8]
Can I train this network on one 1080ti?

**Comment by HarukiYqM** [comment]
> Can I train this network on one 1080ti?

I am not quite sure about this. Since currently I am in travel, I cannot access GPUs. I believe it is ok, but if it is not the case you can reduce memory by reducing patch size/batch size.

**Comment by xsacha** [comment]
You can train anything on anything. Just lower batch size for how much memory you have.
