### ISSUE TITLE
论文问题

### ISSUE THREAD

**Issue by songqi-github** [SHI-Labs/Pyramid-Attention-Networks#9]
作者您好，最近在研读您的论文，有几个问题想请教一下，非常感谢！
1， 在Scale Agnostic Attention这部分中，首先提到在不同尺度下计算feature之间的correlation难点在于空间尺度的不同，于是转换成计算xi与区域描述子zj的联系，个人理解是相当于计算pixel跟对应patch之间的联系，但是这时候尺度依然不相同，是怎么计算correlation的呢？（看代码和论文中是将两个输入进行conv计算correlation的，不是很懂为什么这样就可以计算了，希望作者能够解读一下，非常感谢）
2. 计算好correlation之后利用小尺度feature和softmax之后的correlation，采用deconv的方式去重新构建特征图，但是获得的correlation不是相当于是attention map吗，为什么可以用这个去构建呢

**Comment by HarukiYqM** [comment]
> 作者您好，最近在研读您的论文，有几个问题想请教一下，非常感谢！
> 1， 在Scale Agnostic Attention这部分中，首先提到在不同尺度下计算feature之间的correlation难点在于空间尺度的不同，于是转换成计算xi与区域描述子zj的联系，个人理解是相当于计算pixel跟对应patch之间的联系，但是这时候尺度依然不相同，是怎么计算correlation的呢？（看代码和论文中是将两个输入进行conv计算correlation的，不是很懂为什么这样就可以计算了，希望作者能够解读一下，非常感谢）
> 2. 计算好correlation之后利用小尺度feature和softmax之后的correlation，采用deconv的方式去重新构建特征图，但是获得的correlation不是相当于是attention map吗，为什么可以用这个去构建呢

您好，
1. 在计算correlatiob的时候，我们将整个feature map进行下采样，把采样后的feature map看作未采样feature map的region descriptor。比如下采样两倍，采样后的feature map 上一个pixel feature代表了2*2 区域的信息。conv和dot product是等价操作。
2. convolution的filter是切割后的patch，在attention map上进行反卷积等价于对patch按照attention score加权求和
